dubbo:
  scan:
    base-packages: org.cmcc.service
  protocols:
    dubbo:
      name: dubbo
      port: -1
    rest:
      name: rest
      port: 8080
      server: netty
  registry:
    address: spring-cloud://127.0.0.1:8848
  consumer:
    timeout: 10000
    check: off
    retries: 0
  cloud:
    subscribed-services:
