dubbo:
  scan:
    base-packages: org.cmcc.service
  protocols:
    dubbo:
      name: dubbo
      port: -1
    rest:
      name: rest
      port: 8082
      server: netty
  registry:
    address: spring-cloud://127.0.0.1:8848
  consumer:
    timeout: 10000
    check: off
    retries: 0
  cloud:
    subscribed-services:

spring:
  application:
    name: cmcc-rest-dubbo
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: ${NACOS_PWD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: pcac_cmcc
    url: jdbc:mysql://101.200.86.90/sms?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT&serverTimezone=Asia/Shanghai

