server:
  port: 80

spring:
  application:
    name: sc-gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        - id: web
          uri: lb://cmcc-web-dubbo
          predicates:
            - Path=/api-web/**
          filters:
            - StripPrefix=1
        - id: rest
          uri: lb://cmcc-rest-dubbo
          predicates:
            - Path=/api-rest/**
          filters:
            - StripPrefix=1
        - id: sftp
          uri: lb://sftp-service
          predicates:
            - Path=/sftp-web/**
          filters:
            - StripPrefix=1
        - id: hnzsh
          uri: lb://hnzsh-service
          predicates:
            - Path=/hnzsh-web/**
          filters:
            - StripPrefix=1
