dubbo:
  scan:
    base-packages: org.cmcc.service
  protocols:
    dubbo:
      name: dubbo
      port: -1
  registry:
    address: spring-cloud://127.0.0.1:8848
  consumer:
    timeout: 10000
    check: off
    retries: 0
  cloud:
    subscribed-services: "cmcc-rest-dubbo"
