server:
  port: 8081

spring:
  application:
    name: cmcc-web-dubbo
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
      file-size-threshold: 2KB
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
  messages:
    basename: i18n/messages/messages

file:
  upload-dir: D://UPLOAD

#management:
#  health:
#    mail:
#      enabled: false
#  endpoints:
#    web:
#      base-path: /manage
#      exposure:
#        include: ["*"]

management:
  endpoints:
    web:
      exposure:
        # can be accessed without requiring authentication
        include: "health,info,shutdown,offline,status,metrics,prometheus"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always

dubbo:
  scan:
    base-packages: org.cmcc.service
  protocols:
    dubbo:
      name: dubbo
      port: -1
  registry:
    address: spring-cloud://127.0.0.1:8848
  consumer:
    timeout: 10000
    check: off
    retries: 0
  cloud:
    subscribed-services: "cmcc-rest-dubbo,cmcc-cron-dubbo"
