spring:
  application:
    name: cmcc-cron-dubbo
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: ${NACOS_PWD}
  datasource:
    url: jdbc:mysql://101.200.86.90:3306/sms?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT&serverTimezone=Asia/Shanghai
    username: root
    password: pcac_cmcc
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  kafka:
    bootstrap-servers: 101.200.86.90:9092
    consumer:
      group-id: quartzdemo
      auto-offset-reset: earliest
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    enabled: true
    encoding: UTF-8
    mode: HTML
  messages:
    basename: i18n/messages/messages

# mybatis
mybatis:
  type-aliases-package: org.cmcc.service.bean
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml,classpath:mapping/**/*.xml

dubbo:
  scan:
    base-packages: org.cmcc.quartz
  protocols:
    dubbo:
      name: dubbo
      port: -1
  registry:
    address: spring-cloud://127.0.0.1:8848
  consumer:
    timeout: 10000
    check: off
    retries: 0
  cloud:
    subscribed-services: "cmcc-rest-dubbo"
server:
  port: 8083

actable:
  database:
    type: mysql
  model:
    pack: org.cmcc.quartz.model
  table:
    auto: update

